#!/usr/bin/env node
/* Browser acceptance test. Optional Playwright is a QA dependency only.
   Audio cases use an inert Web Audio mock; they do not validate the missing WAV. */
const {chromium}=require(process.env.CG_PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');const cms=JSON.parse(fs.readFileSync(path.join(root,'assets/data/creator-cms.json')));
const base=(process.argv[2]||'http://127.0.0.1:8818/suzuka-celestial-gate/').replace(/\/?$/,'/');
const output=process.env.CG_QA_OUTPUT||'/private/tmp/celestial-gate-browser';fs.mkdirSync(output,{recursive:true});
const checks=[];let browser;
async function run(name,fn){try{const details=await fn();checks.push({name,status:'PASS',details});console.log('PASS',name)}catch(e){checks.push({name,status:'FAIL',error:e.message});console.log('FAIL',name,e.message)}}
async function session(options={}){const context=await browser.newContext(options);const page=await context.newPage();const issues=[];page.on('pageerror',e=>issues.push(e.message));return{context,page,issues}}
async function home(page){await page.goto(base,{waitUntil:'load'});await page.locator('.cg-world-card').first().waitFor()}
async function audioSession(mode='success'){
 const s=await session();const {page}=s;
 await page.route(base,async route=>{const response=await route.fetch();const body=(await response.text()).replace('"doorAudio":null','"doorAudio":"assets/audio/door-heavy-v2.wav"');await route.fulfill({response,body})});
 await page.route('**/assets/audio/door-heavy-v2.wav',async route=>{if(mode==='slow')await new Promise(r=>setTimeout(r,800));await route.fulfill({status:mode==='http-fail'?404:200,body:''})});
 await page.addInitScript(({mode})=>{
  window._cgMockEvents=[];localStorage.setItem('suzuka.cg.sound','on');
  window.AudioContext=class{constructor(){this.state='suspended';this.currentTime=0;this.destination={};window._cgMockEvents.push({type:'context',at:performance.now()})}resume(){window._cgMockEvents.push({type:'resume',at:performance.now()});if(mode==='rejected')return Promise.reject(new Error('Mock policy refusal'));this.state='running';return Promise.resolve()}decodeAudioData(){return mode==='decode-fail'?Promise.reject(new Error('Mock decode failure')):Promise.resolve({duration:2.2})}createGain(){return{gain:{value:0},connect(){},disconnect(){}}}createBufferSource(){return{connect(){},disconnect(){},start(){window._cgMockEvents.push({type:'start',at:performance.now()})},stop(){window._cgMockEvents.push({type:'stop',at:performance.now()})}}}};
 },{mode});await home(page);return s;
}
(async()=>{
 browser=await chromium.launch({headless:true,executablePath:process.env.CG_CHROME_EXECUTABLE||(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':undefined)});
 await run('Missing formal audio: no preload, no sound, disabled control',async()=>{const{context,page,issues}=await session();const requests=[];page.on('request',r=>{if(/\.wav|\/audio\//.test(r.url()))requests.push(r.url())});await home(page);await page.locator('.cg-settings summary').click();assert(await page.locator('[data-cg-sound]').isDisabled());assert.equal(await page.locator('[data-cg-sound]').textContent(),'音源未登録');assert.equal(requests.length,0);assert.equal(issues.length,0);await context.close()});
 await run('All canonical gates, NOX isolation, skip and browser back',async()=>{const{context,page,issues}=await session({viewport:{width:390,height:844},isMobile:true,hasTouch:true});for(const a of cms.artists){await home(page);const link=page.locator(`[data-cg-world="${a.slug}"]`);await link.click();assert.equal(await page.locator('dialog #cg-door-title').textContent(),a.name);assert.equal(await page.locator('dialog').evaluate(e=>e.classList.contains('cg-infernal')),a.slug==='nox');assert(await page.locator('dialog').evaluate(e=>getComputedStyle(e.querySelector('#cg-door-title')).color===getComputedStyle(e).color),'Gate title uses its own realm text color');await page.waitForTimeout(420);assert(await page.locator('.cg-door-left').evaluate(e=>getComputedStyle(e).transform!=='none'));if(a.slug==='nox')await page.screenshot({path:path.join(output,'nox-door-mobile.png')});await page.locator('.cg-door-skip').click();await page.waitForURL(base+'artists/'+a.slug+'/');assert.equal(await page.locator('body').getAttribute('data-cg-realm'),a.slug==='nox'?'infernal':'celestial');await page.goBack({waitUntil:'load'});assert.equal(await page.locator('dialog[open]').count(),0)}assert.equal(issues.length,0);await context.close();return{artists:cms.artists.length}});
 await run('Keyboard, focus containment, Escape and repeat clicks',async()=>{const{context,page,issues}=await session();await home(page);const link=page.locator('[data-cg-world="asteria"]');await link.focus();await page.keyboard.press('Enter');await page.locator('dialog[open]').waitFor();assert.equal(await page.locator('dialog[open]').count(),1,'Enter opens dialog');await page.evaluate(()=>document.querySelector('[data-cg-world="asteria"]').dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,button:0})));assert.equal(await page.locator('dialog[open]').count(),1,'Repeat click keeps one dialog');await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').getAttribute('class'),'cg-door-cancel');await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await page.locator(':focus').getAttribute('data-cg-world'),'asteria');assert.equal(await page.evaluate(()=>document.body.style.overflow),'');assert.equal(issues.length,0);await context.close()});
 await run('BFCache restore clears an unfinished gate',async()=>{const{context,page}=await session();await home(page);await page.locator('[data-cg-world="asteria"]').click();await page.evaluate(()=>dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await page.evaluate(()=>document.body.style.overflow),'');await page.waitForTimeout(2400);assert.equal(page.url(),base);await context.close()});
 await run('Normal automatic navigation and return to heaven',async()=>{const{context,page}=await session();await home(page);const start=Date.now();await page.locator('[data-cg-world="nox"]').click();await page.waitForURL(base+'artists/nox/');const duration=Date.now()-start;assert(duration>=1900&&duration<5000);await page.locator('[data-cg-return]').click();await page.waitForURL(base);assert.equal(await page.locator('body').getAttribute('data-cg-realm'),'celestial');await context.close();return{observedMs:duration}});
 await run('Persistent short animation and reduced motion',async()=>{const{context,page}=await session({reducedMotion:'reduce'});await home(page);assert.equal(await page.locator('.cg-cloud,.cg-black-flames').count(),0,'Retired illustrated scenery is absent');await page.locator('.cg-settings summary').click();await page.locator('[data-cg-short]').check();await page.reload({waitUntil:'load'});assert(await page.locator('[data-cg-short]').isChecked());const start=Date.now();await page.locator('[data-cg-world="revive"]').click();await page.waitForURL(base+'artists/revive/');assert(Date.now()-start<1800);await context.close()});
 await run('Storage denied: gate still navigates',async()=>{const{context,page,issues}=await session();await page.addInitScript(()=>{Storage.prototype.getItem=()=>{throw new Error('Mock storage denial')};Storage.prototype.setItem=()=>{throw new Error('Mock storage denial')}});await home(page);await page.locator('[data-cg-world="eclypse"]').click();await page.locator('.cg-door-skip').click();await page.waitForURL(base+'artists/eclypse/');assert.equal(issues.length,0);await context.close()});
 await run('Mock only: SFX and visual start share a timeline, mute stops SFX',async()=>{const{context,page}=await audioSession();await page.locator('[data-cg-world="asteria"]').click();await page.waitForFunction(()=>window._cgMockEvents.some(e=>e.type==='start'));await page.waitForTimeout(210);assert(await page.locator('dialog').evaluate(e=>e.classList.contains('cg-door-opening')));await page.keyboard.press('Escape');assert(await page.evaluate(()=>window._cgMockEvents.some(e=>e.type==='stop')));await page.locator('.cg-settings summary').click();await page.locator('[data-cg-sound]').click();assert.equal(await page.locator('[data-cg-sound]').getAttribute('aria-pressed'),'false');await context.close();return{actualWavValidated:false}});
 for(const mode of ['http-fail','decode-fail','rejected','slow'])await run('Mock only: '+mode+' falls back to silent navigation',async()=>{const{context,page,issues}=await audioSession(mode);await page.locator('[data-cg-world="nox"]').click();await page.waitForURL(base+'artists/nox/');assert.equal(issues.length,0);await context.close()});
 await run('Mock only: music active suppresses gate SFX',async()=>{const{context,page}=await audioSession();await page.evaluate(()=>{const video=document.createElement('video');Object.defineProperty(video,'paused',{get:()=>false});Object.defineProperty(video,'ended',{get:()=>false});document.body.append(video)});await page.locator('[data-cg-world="leon-vail"]').click();await page.waitForTimeout(400);assert.equal(await page.evaluate(()=>window._cgMockEvents.filter(e=>e.type==='start').length),0);await page.locator('.cg-door-skip').click();await page.waitForURL(base+'artists/leon-vail/');await context.close()});
 await browser.close();const failures=checks.filter(c=>c.status==='FAIL');fs.writeFileSync(path.join(output,'interaction-results.json'),JSON.stringify({checks,failures:failures.length,actualWavValidated:false},null,2));if(failures.length)process.exitCode=1;
})().catch(e=>{console.error(e.message);process.exitCode=1;browser?.close()});
